-- vim.keymap.del('n', '<C-\\>')
vim.keymap.set('n', '<leader>tt', '<cmd>ToggleTerm<cr>')
vim.keymap.set('t', '<ESC>', '<C-\\><C-N>')
vim.keymap.set('t', '<C-o>', '<C-\\><C-o>:')
vim.keymap.set('t', '<C-w>', [[<C-\><C-n><C-w>]])
